- label: bert-base-uncased-pooled
  type: bert-pooled
  model:
    modules: [embed_bert_pytorch]
    trainable: true
  file: bert-base-uncased
  dsz: 768

- label: bert-base-uncased-pooled-tf
  type: bert-pooled
  model:
    modules: [embed_bert]
    trainable: true
  file: bert_uncased_L-12_H-768_A-12/1
  dsz: 768

